### PR TITLE
Support Transaction Code 53 (PAY)

### PR DESCRIPTION
**Pull request by vkkis93**
Thanks for the nice package.
It's a small PR that allows you to use transaction code 53 (PAY) which works in the same way as ABA.CREDIT.

### CODE REVIEW

**Comment by koresar** [comment]
Superb! I wish there were unit tests for this thing. But, hey. We are not babel or webpack to care about such things. :)

**Comment by koresar** [comment]
Also, I've sent you an invite to this repo. Feel free to accept and push changes directly to this repo (without forks) if needed.

Cheers mate!

**Comment by koresar** [comment]
Published as v1.1

**Comment by vkkis93** [comment]
thanks a lot )

**Pull request merged**
